# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cce175b37127c35574848203bdb81683"
name = "my-personal-cart"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
